[build]
  functions = "functions/fast.py"
  publish = "."  

[build.environment]
  PYTHON_VERSION = "3.10.0"

[functions]
  directory = "functions/fast.py"
  external_node_modules = [
    "fastapi",
    "mangum",
    "jinja2",
    "numpy",
    "pandas",
    "scikit-learn"
  ]
