[build]
  base = "."  # Root directory
  command = "pip install -r requirements.txt"
  
[build.environment]
  PYTHON_VERSION = "3.10.0"
  
[functions]
  directory = "functions"  
  external_node_modules = ["fastapi", "mangum", "jinja2", "numpy", "pandas", "scikit-learn"]
