[build]
  base = "."  # Root directory of the project
  command = "pip install -r requirements.txt"  # Install dependencies
  publish = "."  # Directory to publish (ensure it points to your index.html or output)
  functions = "functions"  # Directory for serverless functions

[build.environment]
  PYTHON_VERSION = "3.10.0"  # Use Python 3.10.0 for your environment

[functions]
  directory = "functions"  # Path to your serverless functions folder
