[build]
  base = "."  # Root directory of the project
  command = """
    pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org fastapi numpy mangum pandas uvicorn &&
    python fast.py
  """
  publish = "."  # Directory to publish (ensure it points to your index.html or output)
  functions = "functions"  # Directory for serverless functions

[build.environment]
  PYTHON_VERSION = "3.10.0"  # Use Python 3.10.0 for your environment

[functions]
  directory = "functions"  # Path to your serverless functions folder
  external_node_modules = ["fastapi", "mangum", "jinja2", "numpy", "pandas", "scikit-learn"]  # Ensure the required Python modules are installed
