[build]
  command ="pip install -r requirements.txt $$uvicorn"
  mainn:app --relad --reload -- host 0.0.0.0 --part 8000
  publish = "functions"  # Directory to publish (ensure it points to your index.html or output)

[build.environment]
  PYTHON_VERSION = "3.10.0"  # Use Python 3.10.0 for your environment

[functions]
  directory = "functions"  # Path to your serverless functions folder
